### ISSUE TITLE
Wrong formatting of orange disruptions count indicator

### ISSUE THREAD

**Issue by afoeder** [Akii/elescore#1]
Orange thingie in the upper right corner…
![image](https://user-images.githubusercontent.com/1125168/29653860-72ccaf26-88ab-11e7-882e-f723a22e5fa0.png)

is in the wrong formatting because the number is a child of the fa-warning icon which is not correct.
Wrong, current code:
```
<li class="dropdown dropdown-dark">
<i class="fa fa-warning fa-2x" style="padding: 20px; margin-right: 65px; color: orange;">&nbsp;169</i>
</li>
```

Correction proposal:
```
<li class="dropdown dropdown-dark" style="color: orange;">
  <i class="fa fa-warning fa-2x"></i>
  <span style="font-size: 2em;">169</span>
</li>
```
(tested in DOM)

**Comment by Akii** [comment]
Thank you for your bug report, kind sir. This is much appreciated!

**Comment by Akii** [comment]
Fixed in production.
